version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"